// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1545722810);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1545752588);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1546602925);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545680419);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1545680539);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1545752708);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1545590829);
user_pref("browser.laterrun.bookkeeping.sessionCount", 10);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{da858bae-28d8-40e9-98ad-d7b60a282061}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1545676200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1546602899368");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1546604707368");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1546602900855");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1546606500855");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181212012434");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1546602895");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181212012434");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"ublock0_raymondhill_net-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1545590833402");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Wed, 19 Dec 2018 15:09:47 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1545722815);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181212012434");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4e9bc6d5-0689-4c1f-b908-9b511f09bfbb\",\"screenshots@mozilla.org\":\"c97cdfc0-92dd-4f89-a627-fb81a9fb198e\",\"webcompat-reporter@mozilla.org\":\"f3b388e5-b0cb-40b9-a3ad-0c99a18dc026\",\"webcompat@mozilla.org\":\"9d607e0b-af24-48f3-aee7-9800c7d39e79\",\"uBlock0@raymondhill.net\":\"63b33322-7c27-468b-b9c1-b43b3d59a568\"}");
user_pref("lightweightThemes.persisted.headerURL", true);
user_pref("lightweightThemes.selectedThemeID", "923464");
user_pref("lightweightThemes.usedThemes", "[{\"id\":\"923464\",\"name\":\"Youtube\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/923464/header.png?modified=51c8e89f\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/923464/icon.png?modified=51c8e89f\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/923464/preview.png?modified=51c8e89f\",\"author\":\"DerBloecker\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/923464\",\"version\":\"1.0\"}]");
user_pref("media.gmp-manager.buildID", "20181212012434");
user_pref("media.gmp-manager.lastCheck", 1545722815);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.peerconnection.ice.proxy_only", true);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d12055ac-2294-4a9a-8e78-803f4e81e92c");
user_pref("security.sandbox.plugin.tempDirSuffix", "5978a6ed-49ff-40c9-b6e0-8f6740984a90");
user_pref("services.blocklist.addons.checked", 1545680538);
user_pref("services.blocklist.gfx.checked", 1545680538);
user_pref("services.blocklist.onecrl.checked", 1545680538);
user_pref("services.blocklist.pinning.checked", 1545680538);
user_pref("services.blocklist.plugins.checked", 1545680538);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1545680538);
user_pref("services.settings.main.language-dictionaries.last_check", 1545680538);
user_pref("services.settings.main.onboarding.last_check", 1545680538);
user_pref("services.settings.main.sites-classification.last_check", 1545680538);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1546602894);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20181212012434");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
