// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "5a472758-2969-4c25-a1a9-360461f5d1a8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1545680639);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1545590109);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545591529);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1545680519);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1545590079);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c0f88128-0215-4591-b2e6-c9cbeaad8997}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1545676200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacy.trackingprotection.menu", "private");
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1545680493480");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1545682295480");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1545680495577");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1545684095577");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181212012434");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1545680490");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181212012434");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1545590084156");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "f06a2927f1b04ae0b08be334d9458ca8");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1545680641);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181212012434");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{4cd5f9e7-c7e1-4f24-8e70-9ff3d22a2357}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"26364940-8191-4a81-a089-9c3531b696e1\",\"screenshots@mozilla.org\":\"287f7484-9140-4132-82b9-da012a0b03b7\",\"webcompat-reporter@mozilla.org\":\"b24800d2-60d0-4577-8c46-a42f069959fa\",\"webcompat@mozilla.org\":\"8a62ce9a-d90d-4b22-8bcc-2f2544e8da4c\",\"fxmonitor@mozilla.org\":\"fe86c206-5d37-4f2c-b4be-afb17dea999c\"}");
user_pref("lightweightThemes.persisted.headerURL", true);
user_pref("lightweightThemes.selectedThemeID", "19051");
user_pref("lightweightThemes.usedThemes", "[{\"id\":\"19051\",\"name\":\"warning biohazard\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/19051/biohazardhead.jpg?modified=1239808800\",\"textcolor\":\"#f2e9e9\",\"accentcolor\":\"#faf0f0\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/19051/preview_small.jpg?modified=1239808800\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/19051/preview.jpg?modified=1239808800\",\"author\":\"fabart\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/19051\",\"version\":\"0\",\"updateDate\":1545680641199,\"installDate\":1545680563335}]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1545591577);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181212012434");
user_pref("media.gmp-manager.lastCheck", 1545591576);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e4c33a5b-76d3-47f1-b67e-e5ceb1039c35");
user_pref("security.sandbox.plugin.tempDirSuffix", "35dd9bca-6230-49a7-9381-a62597ea4ac9");
user_pref("services.blocklist.addons.checked", 1545680614);
user_pref("services.blocklist.gfx.checked", 1545680614);
user_pref("services.blocklist.onecrl.checked", 1545680614);
user_pref("services.blocklist.pinning.checked", 1545680614);
user_pref("services.blocklist.plugins.checked", 1545680614);
user_pref("services.settings.clock_skew_seconds", -7);
user_pref("services.settings.last_etag", "\"1545434118736\"");
user_pref("services.settings.last_update_seconds", 1545680526);
user_pref("services.settings.main.language-dictionaries.last_check", 1545680614);
user_pref("services.settings.main.onboarding.last_check", 1545680614);
user_pref("services.settings.main.sites-classification.last_check", 1545680614);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1545680488);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20181212012434");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
