// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "fa449392-aec6-475d-b6fe-b664202d10ef");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1545679458);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1545679578);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1545591360);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545591445);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1545679338);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1545679818);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1545679698);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1545591203);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ae178047-459a-4b77-9eea-b528f4349538}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1545676200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacy.trackingprotection.menu", "private");
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1545679284756");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1545681070756");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1545679286734");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1545682886734");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181212012434");
user_pref("browser.slowStartup.averageTime", 772);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181212012434");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1545591207640");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "af9c978dc8f84337a17886c45e7ca16e");
user_pref("extensions.blocklist.lastModified", "Wed, 19 Dec 2018 15:09:47 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1545679460);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181212012434");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{91bea273-0aae-462f-94aa-d44164524b22}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"11998f68-1166-4c8d-b018-085e1136ea11\",\"screenshots@mozilla.org\":\"0c71a9fe-2da2-44ec-b471-4c26c5fc2241\",\"webcompat-reporter@mozilla.org\":\"568ed310-efd3-4570-900a-1217dcaaee9d\",\"webcompat@mozilla.org\":\"463ffed2-954c-4cbf-af99-d7627aeeb2ee\",\"fxmonitor@mozilla.org\":\"6da00334-60e7-43a3-bba9-016613abbd39\"}");
user_pref("lightweightThemes.persisted.headerURL", true);
user_pref("lightweightThemes.selectedThemeID", "483569");
user_pref("lightweightThemes.usedThemes", "[{\"id\":\"483569\",\"name\":\"Netflix\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/483569/header.png?modified=fe0d06a8\",\"textcolor\":\"#ffffff\",\"accentcolor\":\"#cc0000\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/483569/icon.png?modified=fe0d06a8\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/483569/preview.png?modified=fe0d06a8\",\"author\":\"Johnny2000\",\"description\":\"My first theme. I tried to make it look best in a minimal browser configuration, without toolbar and bookmarks.\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/483569\",\"version\":\"1.0\",\"updateDate\":1545680301161,\"installDate\":1545680301161},{\"id\":\"18066\",\"name\":\"Dark Fox\",\"headerURL\":\"https://addons.cdn.mozilla.net/user-media/addons/18066/1232849758499.jpg?modified=1241547734\",\"textcolor\":\"#ffffff\",\"accentcolor\":\"#000000\",\"iconURL\":\"https://addons.cdn.mozilla.net/user-media/addons/18066/preview_small.jpg?modified=1241547734\",\"previewURL\":\"https://addons.cdn.mozilla.net/user-media/addons/18066/preview_large.jpg?modified=1241547734\",\"author\":\"randomaster\",\"description\":\"My dark version of the Firefox logo.\",\"updateURL\":\"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/18066\",\"version\":\"1.0\",\"updateDate\":1545680281194,\"installDate\":1545680281194}]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1545679352);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181212012434");
user_pref("media.gmp-manager.lastCheck", 1545679351);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "bd8d9b46-2a6f-4f9e-b7cf-63b8263b0ec6");
user_pref("security.sandbox.plugin.tempDirSuffix", "d006291e-0407-4c5f-a69b-7a10cd3b1df8");
user_pref("services.blocklist.addons.checked", 1545679338);
user_pref("services.blocklist.gfx.checked", 1545679338);
user_pref("services.blocklist.onecrl.checked", 1545679338);
user_pref("services.blocklist.pinning.checked", 1545679338);
user_pref("services.blocklist.plugins.checked", 1545679338);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1545434118736\"");
user_pref("services.settings.last_update_seconds", 1545679338);
user_pref("services.settings.main.language-dictionaries.last_check", 1545679338);
user_pref("services.settings.main.onboarding.last_check", 1545679338);
user_pref("services.settings.main.sites-classification.last_check", 1545679338);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1545679308);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20181212012434");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
